# Generated by Django 2.0.4 on 2018-04-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180405_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='exp',
            field=models.PositiveIntegerField(default=0, verbose_name='EXP'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
