# Generated by Django 2.0.4 on 2018-04-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180413_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='exp',
        ),
    ]
