# Generated by Django 2.0.4 on 2018-04-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180413_0808'),
        ('transcription', '0004_auto_20180413_1155'),
        ('accounts', '0004_remove_user_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='learning_languages',
            field=models.ManyToManyField(through='transcription.Proficiency', to='core.Language'),
        ),
    ]
