# Generated by Django 2.0.4 on 2018-05-30 07:38

from django.db import migrations
import glossm.utils
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180523_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=glossm.utils.RenamedPath('profile_images', 'user')),
        ),
    ]
