# Generated by Django 2.0.4 on 2018-04-22 06:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('transcription', '0001_initial'), ('transcription', '0002_auto_20180405_1050'), ('transcription', '0003_auto_20180413_0704'), ('transcription', '0004_auto_20180413_1155')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20180413_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=100)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='core.Record')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Submission',
            }
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.PositiveIntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proficiency', to='core.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proficiency', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Proficiency',
                'db_table': 'Proficiency',
            },
        ),
        migrations.AlterUniqueTogether(
            name='proficiency',
            unique_together={('user', 'language')},
        ),
    ]
