# Generated by Django 2.0.4 on 2018-04-05 08:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('name', models.CharField(max_length=50)),
                ('num_speakers', models.PositiveIntegerField(verbose_name='number of speakers')),
                ('endangerment', models.CharField(choices=[('0', 'International (0)'), ('1', 'National (1)'), ('2', 'Provincial (2)'), ('3', 'Wider Communication (3)'), ('4', 'Educational (4)'), ('5', 'Developing (5)'), ('6a', 'Vigorous (6a)'), ('6b', 'Threatened (6b)'), ('7', 'Shifting (7)'), ('8a', 'Moribund (8a)'), ('8b', 'Nearly Extinct (8b)'), ('9', 'Dormant (9)'), ('10', 'Extinct (10)')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_code', models.CharField(max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='ASK code')),
                ('in_en', models.CharField(max_length=100, verbose_name='in English')),
                ('in_ko', models.CharField(max_length=100, verbose_name='in Korean')),
                ('in_ru', models.CharField(max_length=100, verbose_name='in Russian')),
                ('in_zh', models.CharField(max_length=100, verbose_name='in Chinese')),
                ('in_mn', models.CharField(max_length=100, verbose_name='in Mongolian')),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.URLField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transcription.Language')),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transcription.Meaning')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=100)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transcription.Record')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('language', 'meaning')},
        ),
    ]
