# Generated by Django 2.0.4 on 2018-05-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_squashed_0004_auto_20180413_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
