# Generated by Django 2.0.4 on 2018-04-05 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='transcription.Language'),
        ),
        migrations.AlterField(
            model_name='record',
            name='meaning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='transcription.Meaning'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='transcription.Record'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
