# Generated by Django 2.0.4 on 2018-04-13 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20180413_0808'),
        ('transcription', '0003_auto_20180413_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.PositiveIntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proficiency', to='core.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proficiency', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Proficiency',
                'db_table': 'Proficiency',
            },
        ),
        migrations.AlterUniqueTogether(
            name='proficiency',
            unique_together={('user', 'language')},
        ),
    ]
