# Generated by Django 2.0.4 on 2018-06-09 11:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import glossm.utils


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_auto_20180413_0808'), ('core', '0003_auto_20180530_0738'), ('core', '0004_auto_20180530_1504'), ('core', '0005_auto_20180604_0804')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('name', models.CharField(max_length=50)),
                ('num_speakers', models.PositiveIntegerField(verbose_name='number of speakers')),
                ('endangerment', models.CharField(choices=[('0', 'International (0)'), ('1', 'National (1)'), ('2', 'Provincial (2)'), ('3', 'Wider Communication (3)'), ('4', 'Educational (4)'), ('5', 'Developing (5)'), ('6a', 'Vigorous (6a)'), ('6b', 'Threatened (6b)'), ('7', 'Shifting (7)'), ('8a', 'Moribund (8a)'), ('8b', 'Nearly Extinct (8b)'), ('9', 'Dormant (9)'), ('x10', 'Extinct (10)')], max_length=2)),
            ],
            options={
                'db_table': 'Language',
            },
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_code', models.CharField(max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='ASK code')),
                ('en', models.CharField(max_length=100, verbose_name='in English')),
                ('ko', models.CharField(max_length=100, verbose_name='in Korean')),
                ('ru', models.CharField(max_length=100, verbose_name='in Russian')),
                ('zh', models.CharField(max_length=100, verbose_name='in Chinese')),
                ('mn', models.CharField(max_length=100, verbose_name='in Mongolian')),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'Meaning',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to=glossm.utils.RenamedPath('audio', 'record'))),
                ('video', models.FileField(blank=True, null=True, upload_to=glossm.utils.RenamedPath('video', 'record'))),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.Language')),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.Meaning')),
            ],
            options={
                'db_table': 'Record',
            },
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('language', 'meaning')},
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Topic',
            },
        ),
        migrations.CreateModel(
            name='TopicSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TopicSet',
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='core.TopicSet'),
        ),
        migrations.AddField(
            model_name='language',
            name='topic_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='languages', to='core.TopicSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meaning',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='meanings', to='core.Topic'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('topic_set', 'name')},
        ),
    ]
