# Generated by Django 2.0.4 on 2018-04-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Topic',
            },
        ),
        migrations.CreateModel(
            name='TopicSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TopicSet',
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='core.TopicSet'),
        ),
        migrations.AddField(
            model_name='language',
            name='topic_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='languages', to='core.TopicSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meaning',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='meanings', to='core.Topic'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('topic_set', 'name')},
        ),
    ]
