# Generated by Django 2.0.4 on 2018-06-09 11:31

import random
from string import ascii_uppercase

from django.db import migrations, models


def set_topic_codes(apps, schema_editor):
    Topic = apps.get_model('core', 'Topic')
    for topic in Topic.objects.all():
        chars = random.choices(ascii_uppercase, k=3)
        topic.code = ''.join(chars)
        topic.save()


def set_topic_set_codes(apps, schema_editor):
    TopicSet = apps.get_model('core', 'TopicSet')
    for topic_set in TopicSet.objects.all():
        chars = random.choices(ascii_uppercase, k=3)
        topic_set.code = ''.join(chars)
        topic_set.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0005_auto_20180604_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='code',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topicset',
            name='code',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='endangerment',
            field=models.CharField(blank=True, choices=[('0', 'International (0)'), ('1', 'National (1)'), ('2', 'Provincial (2)'), ('3', 'Wider Communication (3)'), ('4', 'Educational (4)'), ('5', 'Developing (5)'), ('6a', 'Vigorous (6a)'), ('6b', 'Threatened (6b)'), ('7', 'Shifting (7)'), ('8a', 'Moribund (8a)'), ('8b', 'Nearly Extinct (8b)'), ('9', 'Dormant (9)'), ('x10', 'Extinct (10)')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='num_speakers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='number of speakers'),
        ),
        migrations.RunPython(set_topic_codes),
        migrations.RunPython(set_topic_set_codes),
        migrations.AlterField(
            model_name='topic',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='topicset',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
