# Generated by Django 2.0.4 on 2018-06-30 15:43

from django.db import migrations, models
import glossm.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180609_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='wave_image',
            field=models.FileField(blank=True, null=True, upload_to=glossm.utils.RenamedPath('wave', 'record')),
        ),
    ]
