# Generated by Django 2.0.4 on 2018-05-30 07:38

from django.db import migrations, models
import glossm.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180413_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=glossm.utils.RenamedPath('audio', 'record')),
        ),
        migrations.AlterField(
            model_name='record',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=glossm.utils.RenamedPath('video', 'record')),
        ),
    ]
