# Generated by Django 2.0.4 on 2018-05-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180530_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meaning',
            old_name='in_en',
            new_name='en',
        ),
        migrations.RenameField(
            model_name='meaning',
            old_name='in_ko',
            new_name='ko',
        ),
        migrations.RenameField(
            model_name='meaning',
            old_name='in_mn',
            new_name='mn',
        ),
        migrations.RenameField(
            model_name='meaning',
            old_name='in_ru',
            new_name='ru',
        ),
        migrations.RenameField(
            model_name='meaning',
            old_name='in_zh',
            new_name='zh',
        ),
    ]
