# Generated by Django 2.0.4 on 2018-06-04 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180530_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='language',
            name='endangerment',
            field=models.CharField(choices=[('0', 'International (0)'), ('1', 'National (1)'), ('2', 'Provincial (2)'), ('3', 'Wider Communication (3)'), ('4', 'Educational (4)'), ('5', 'Developing (5)'), ('6a', 'Vigorous (6a)'), ('6b', 'Threatened (6b)'), ('7', 'Shifting (7)'), ('8a', 'Moribund (8a)'), ('8b', 'Nearly Extinct (8b)'), ('9', 'Dormant (9)'), ('x10', 'Extinct (10)')], max_length=2),
        ),
    ]
