# Generated by Django 2.0.4 on 2018-06-22 02:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import glossm.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180604_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Informant ID')),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male'), ('X', 'others/unknown')], max_length=3)),
                ('date_of_birth', models.DateField(blank=True)),
                ('geo_location', models.CharField(blank=True, max_length=50)),
                ('picture_path', models.FileField(blank=True, null=True, upload_to=glossm.utils.RenamedPath('picture', 'informant'))),
            ],
            options={
                'db_table': 'Informant',
            },
        ),
        migrations.AddField(
            model_name='record',
            name='footnote',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='language',
            name='endangerment',
            field=models.CharField(choices=[('0', 'International (0)'), ('1', 'National (1)'), ('2', 'Provincial (2)'), ('3', 'Wider Communication (3)'), ('4', 'Educational (4)'), ('5', 'Developing (5)'), ('6a', 'Vigorous (6a)'), ('6b', 'Threatened (6b)'), ('7', 'Shifting (7)'), ('8a', 'Moribund (8a)'), ('8b', 'Nearly Extinct (8b)'), ('9', 'Dormant (9)'), ('x10', 'Extinct (10)')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='informant',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informants', to='core.Language'),
        ),
    ]
